const PREFIX = "/";
const path = {
    Root: PREFIX + '',
    Home: PREFIX + '',
    Login: PREFIX + 'login',
    Dashboard: PREFIX + 'dashboard',
    ForgotPassword: PREFIX + 'forgotpassword',
    ResetPassword: PREFIX + 'resetpassword',
    // RMList: PREFIX + 'rm',
    // RMCreate: PREFIX + 'rm/create',
    // RMUpdate: PREFIX + 'rm/update',
    // DealerList: PREFIX + 'dealer',
    // DealerCreate: PREFIX + 'dealer/create',
    // DealerUpdate: PREFIX + 'dealer/update',
    // Inventory: PREFIX + 'inventory',
    // InventoryCreate: PREFIX + 'inventory/create',
    // InventoryUpdate: PREFIX + 'inventory/update',
    // TestDrive: PREFIX + 'test-drive',
    // TestDriveCreate: PREFIX + 'test-drive/create',
    // TestDriveUpdate: PREFIX + 'test-drive/update',
    // CampaginsList: PREFIX + 'deal-configurator/campaign',
    // FinanceList: PREFIX + 'deal-configurator/finance',
    // CampaginsCreate: PREFIX + 'campaign/create',
    // CampaginsEdit: PREFIX + 'deal-configurator/campaign/edit/:editCampaign',
    // CampaginsView: PREFIX + 'deal-configurator/campaign/view/:editCampaign',
    // Slots: PREFIX + 'test-drive/slot/:editSlot',
    // DealConfigurator: PREFIX + 'deal-configurator',
    // FinanceCreate: PREFIX + 'deal-configurator/finance/create',
    // FinanceEdit: PREFIX + 'deal-configurator/finance/edit/:editFinance',
    // FinanceView: PREFIX + 'deal-configurator/finance/view/:editFinance',
    // Insurance: PREFIX + 'deal-configurator/insurance',
};

export default path;
