export default {
    env: 'production',
    cors: 1,
    logs: 1,
    isStackTrace: 1,
    baseUrl : "http://3.145.103.66/api/v1/",
    // apiBaseUrl: 'http://app.connecto.io/newconnecto/',
    // apiServerBaseUrl: 'http://app.connecto.io/newconnecto/',
    apiBaseUrl: 'https://bookWrench-prod.cardekho.com/api/v1/',
    apiServerBaseUrl: 'https://app.connecto.io/',
    jobsBaseUrl: 'https://jobs.connecto.io/',
    appBaseUrl: 'https://api.connecto.io/',
    imgPath: 'https://img.gaadicdn.com/pwa/img/',
    imgpath2: 'https://img2.gaadicdn.com/',
    staticServer: 'https://stagingstatic.cardekho.com',
    localImgPath: '/pwa/img',
    localFontPath: '/pwa/font',
    jsAssetPath: '/pwa/js',
    cssAssetPath: '/pwa/css',
    gtmId: '',
    otherAPIDomain: {},
};
