// Local configs

export default {
    env: 'local',
    cors: 1,
    logs: 1,
    isStackTrace: 1,
    baseUrl: 'http://localhost:4002/api/v1/',
   // baseUrl: 'http://bookwrench.gswire.com/api/v1/',
    //apiBaseUrl: 'http://app.connecto.io/',
    //apiServerBaseUrl: 'http://app.connecto.io/',
    //apiBaseUrl: 'http://192.168.1.10:3005/',
    //apiServerBaseUrl: 'http://192.168.1.10:3005/',
    jobsBaseUrl: 'http://192.168.35.15:3010/',
    // apiBaseUrl: 'http://localhost:8081/api/v1/',
    apiBaseUrl: '/api/v1/',
    //apiBaseUrl:'http://ec90fe72f015.ngrok.io/api/v1',
    //appBaseUrl:'https://api.connecto.io/',
    // apiServerBaseUrl: 'http://staging-app.connecto.io/',
    imgPath: 'https://img.gaadicdn.com/pwa/img/',
    imgpath2: 'https://img2.gaadicdn.com/',
    staticServer: 'https://stagingstatic.cardekho.com',
    localImgPath: '/pwa/img',
    localFontPath: '/pwa/font',
    jsAssetPath: '/pwa/js',
    cssAssetPath: '/pwa/css',
    gtmId: 'GTM-WG2J6S',
    cookieDomain: 'localhost',
    otherAPIDomain: {},
};
